"""migracion_inicial_clientes

Revision ID: 3eec652277f3
Revises: b8f5e1889860
Create Date: 2026-07-03 23:18:42.092697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eec652277f3'
down_revision: Union[str, None] = 'b8f5e1889860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
