"""crear_tablas

Revision ID: d49036308305
Revises: 
Create Date: 2026-07-04 01:09:00.668201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd49036308305'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('primer_nombre', sa.String(length=100), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=100), nullable=True),
    sa.Column('primer_apellido', sa.String(length=100), nullable=False),
    sa.Column('segundo_apellido', sa.String(length=100), nullable=True),
    sa.Column('dni_actual', sa.String(length=20), nullable=False),
    sa.Column('telefono_principal', sa.String(length=20), nullable=False),
    sa.Column('telefono_alternativo', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telegram_user', sa.String(length=100), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.Column('direccion_recogida', sa.Text(), nullable=False),
    sa.Column('nombre_destinatario_py', sa.String(length=200), nullable=False),
    sa.Column('telefono_destinatario_py', sa.String(length=20), nullable=False),
    sa.Column('direccion_destino_py', sa.Text(), nullable=False),
    sa.Column('fecha_alta', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_dni_actual'), 'clientes', ['dni_actual'], unique=False)
    op.create_index(op.f('ix_clientes_telefono_principal'), 'clientes', ['telefono_principal'], unique=False)
    op.create_table('contenedores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero_contenedor', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.Enum('llenando', 'cerrado', 'en_transito', 'llego', 'distribuyendo', 'completado', name='estadocontenedor'), nullable=False),
    sa.Column('capacidad_m3', sa.Float(), nullable=True),
    sa.Column('volumen_ocupado_m3', sa.Float(), nullable=False),
    sa.Column('fecha_apertura', sa.Date(), nullable=False),
    sa.Column('fecha_cierre', sa.Date(), nullable=True),
    sa.Column('fecha_envio', sa.Date(), nullable=True),
    sa.Column('fecha_llegada_paraguay', sa.Date(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contenedores_numero_contenedor'), 'contenedores', ['numero_contenedor'], unique=True)
    op.create_table('envios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('contenedor_id', sa.UUID(), nullable=True),
    sa.Column('descripcion_producto', sa.Text(), nullable=False),
    sa.Column('peso_kg', sa.Float(), nullable=True),
    sa.Column('volumen_m3', sa.Float(), nullable=True),
    sa.Column('precio_total', sa.Float(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente_recogida', 'recogido', 'en_almacen', 'asignado_contenedor', 'en_transito', 'llego_paraguay', 'en_distribucion', 'entregado', name='estadoenvio'), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_recogida_pactada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_recogida_real', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_entrega', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qr_code_url', sa.Text(), nullable=True),
    sa.Column('firma_url', sa.Text(), nullable=True),
    sa.Column('fotos_urls', sa.Text(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['contenedor_id'], ['contenedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_envios_codigo'), 'envios', ['codigo'], unique=True)
    op.create_table('historial_cambios_cliente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('campo_modificado', sa.String(length=100), nullable=False),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_nuevo', sa.Text(), nullable=True),
    sa.Column('fecha_cambio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_cambio', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('envio_id', sa.UUID(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('tipo', sa.Enum('inicial', 'parcial', 'saldo', 'total', name='tipopago'), nullable=False),
    sa.Column('metodo', sa.Enum('efectivo', 'transferencia', 'bizum', name='metodopago'), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'declarado_cliente', 'verificado', 'rechazado', name='estadopago'), nullable=False),
    sa.Column('declarado_por_cliente', sa.Boolean(), nullable=False),
    sa.Column('comprobante_url', sa.Text(), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_verificacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verificado_por', sa.String(length=100), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['envio_id'], ['envios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos')
    op.drop_table('historial_cambios_cliente')
    op.drop_index(op.f('ix_envios_codigo'), table_name='envios')
    op.drop_table('envios')
    op.drop_index(op.f('ix_contenedores_numero_contenedor'), table_name='contenedores')
    op.drop_table('contenedores')
    op.drop_index(op.f('ix_clientes_telefono_principal'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_dni_actual'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
